### ISSUE TITLE
JTable com outra JFrame

### ISSUE THREAD

**Issue by andrelucassvt** [andrelucassvt/Hospital-sistema-de-senhas#6]
Não consigo jogar os dados da JInternalFrame "CadastroDeFuncionario" na outra JInternalFrame "Lista" que contem uma JTable aonde quero colocar os dados.

**Comment by andrelucassvt** [comment]
@Diogo-Felipe

**Comment by tiagoadmstz** [comment]
Issue JTable com outra JFrame correction by pull request.
